### ISSUE TITLE
Can't delete node from Uchiwa interface

### ISSUE THREAD

**Issue by Jinkxed** [sensu/uchiwa#168]
When I try to delete a node from the clients screen, I get a message saying:

<strong>Error</strong> The client was not deleted! 400

Am I missing some credentials or something somewhere that will allow this?

**Comment by KwanzooDev** [comment]
How to delete checks from Uchiwa UI. I have implemented few checks for particulat server but now i want to remove some of them. There are no options to delete checks.

**Comment by palourde** [comment]
Hi @KwanzooDev 

You can't delete checks from Uchiwa, you can only silence them or resolve an event associated to them. Removing a particular check must be done at the sensu-client level. Then, you can delete the client within Uchiwa in order to remove the checks history of this particular client.

**Comment by KwanzooDev** [comment]
1> I have 1 server and 2 client. In one client i have tomcat install and other i have httpd installed, written ruby scripts for both tomcat and httpd in each server . But In Uchiwa UI i an getting error as "sh: /etc/sensu/plugins/check-httpd.rb: No such file or directory". for the client which has only tomcat and vice versa.
Is there a way to make services to particular client instead of global?
