### ISSUE TITLE
Unauthenticated read-only view

### ISSUE THREAD

**Issue by msnelling** [sensu/uchiwa#216]
It would be great, in the absence of an advanced authentication/authorization scheme, to have the option of a read-only view for unauthenticated users.

This view would remove the ability to delete clients and create stashes, functioning purely as a dashboard.

**Comment by iiro** [comment]
:+1:

**Comment by wilshire461** [comment]
:+1:

**Comment by shearn89** [comment]
:+1:, this would be extremely useful!

**Comment by palourde** [comment]
For anyone interested, we implemented the RBAC concept (which support authenticated read-only users) into the [Sensu Enterprise](http://sensuapp.org/enterprise) dashboard. It might be, at some point in the future, released as an open-source feature into Uchiwa.

Supporting unauthenticated read-only users in comparaison of authenticated read-only users would require an enormous amount of work and add some complexity so because of these reasons, I won't work on it. However, if anyone is interested in implementing this feature in a clean manner, let me know, it will be my pleasure to assist you if you have any questions.

**Comment by belminf** [comment]
I see that it's been a year since this feature was rejected. Is this still not being considered?

**Comment by rodriguesalex** [comment]
:+1:

**Comment by palourde** [comment]
@belminf @rodriguesalex This feature is now implemented, see the documentation here: http://docs.uchiwa.io/en/latest/configuration/uchiwa/#multiple-users-with-simple-authentication

**Comment by rodriguesalex** [comment]
@palourde thanks ..... i think i was confusing this with the API.

I was actually looking to provide our developers with read-only access to the Sensu API so that they can query some checks. Do you happen to know if the API supports this, and if there is another thread you can point me to?

**Comment by palourde** [comment]
@rodriguesalex Unfortunately the Sensu API itself does not implement any RBAC system. We might have a public API available directly from Uchiwa at some point however.
