### ISSUE TITLE
Command details on a node's 'check details' page misleading

### ISSUE THREAD

**Issue by gpaszkowski-rmn** [sensu/uchiwa#230]
The command field displayed on the 'check details' section for a particular node displays the command from the sensu server, not the command from the client.  This is misleading as the command is not the client configured command and should probably be removed until the sensu API can return this information.

**Comment by calebhailey** [comment]
This may already be fixed in newer Uchiwa releases, which take advantage of a newer "Sensu Results API" to show check configuration details. Having said that, we do need to improve the documentation to explain how the Sensu API loads configuration (and when configuration needs to be reloaded), which is ultimately the data that is displayed in Uchiwa.
