### ISSUE TITLE
Various parts of the UI break if there is a "/" in a DC name

### ISSUE THREAD

**Issue by mattrobenolt** [sensu/uchiwa#279]
We set up Uchiwa, and one of our DCs was named `dal05 / dal09`, and the url becomes: `/#/client/dal05%20/%20dal09/<node>`. I assume this extra / in the url is causing some issues on the frontend.

**Comment by palourde** [comment]
Thanks @mattrobenolt for reporting this issue, I'll try to have a fix released within the next release.

**Comment by palourde** [comment]
After some investigation, it looks like replacing `encodeURI` with `encodeURIComponent` in the [go](https://github.com/sensu/uchiwa-web/blob/master/js/services.js#L207) method, in order to escape characters like **/**, would require a good amount of work.

For now, I'll decrease the priority of this issue and you should avoid using the characters **:** **/** **;** and **?** in a datacenter or client name. I'll update the documentation to reflect this limitation. I'll gladly accept a PR for this issue, otherwise I'll work on it once the other issues with greater priority are completed.
