### ISSUE TITLE
Support external authentication via passed-through headers

### ISSUE THREAD

**Issue by rmc3** [sensu/uchiwa#295]
We have a large number of users who need to be able to work with Uchiwa. Some should be read only. For those that aren't, we'd like to be able to record which users created which stashes. This is possible via Uchiwa's built in authentication. However, managing all of these users and their credentials separately in Uchiwa is something we'd like to avoid, given that we already maintain these users in a "single source of truth" directory outside of Uchiwa.

Given this, it would be useful to be able to authenticate users in Uchiwa via passed through headers from an upstream proxy. This would allow the upstream proxy (such as Apache) to handle the complexity of external authentication. 

This could be implemented by having Uchiwa looking for a header such as `X-Remote-User` and treating the value of that header as the username if it exists.

Thoughts?

**Comment by palourde** [comment]
Hi @rmc3 

Built-in external authentication will be supported within the [Sensu Enterprise](http://sensuapp.org/enterprise) dashboard, which is based on Uchiwa. Because of it, I won't work on supporting alternative external authentication methods however if you are interested in building and adding this feature to Uchiwa, it will be my pleasure to assist you if you have any questions.

**Comment by psychonaut** [comment]
Don't want to create another issue so forgive me for adding it here.

I am using uchiwa with nginx proxy + ldap authentication. I would like to uchiwa uses headers provided by nginx to display name (and use it in actions) provided by basic auth headers.

**Comment by gsalisbury** [comment]
Hi @palourde
I would like this feature as well, and would like to have a go at adding it. Would you be able to provide some hints as to how to proceed?

**Comment by ctheune** [comment]
I'd love to step in but my Go knowledge is very limited. :( Any pointers how to get started? I see that we'd have to add a separate provider and there is some structure for "advanced" already in place, but it's hard for me to follow the flow around how this can be configured and where I would get access to the request.

**Comment by UnitedMarsupials** [comment]
The sad reality is, Uchiwa is not doing anything useful with the username even when one is available. The only place, where the username _could_ currently be used -- stashing an alert through Uchiwa's interface -- does not record the username (see #542).

So, there is nothing to gain (currently) from making Uchiwa aware of the username. Instead you may as well bind Uchiwa to 127.0.0.1 (instead of the promiscuous 0.0.0.0) and place an authenticating proxy (such as Apache) in front of it -- and implement your authentication-requirements in the proxy. I, for example, use Apache's `mod_ldap` to authenticate users against our AD.

When listening only to 127.0.0.1, assuming you trust local users on the server, you can run Uchiwa without authentication. Or you can use your favourite configuration-management tool (we use Puppet here) to generate the list of authorized users _and their `accessToken`s_. The simplest is to use the username as the `accessToken`:
```json
                "Users": [
                        {
                                "username":     "admin",
                                "accessToken":  "admin",
                                "password": "*",
                                "readonly":     false
                        },
```
Then, configure the proxy to replace the `Authorization`-header with the user's token. For example, with Apache-2.4 you'd use something like this:
```apache
<VirtualHost	*:443>
	SSLEngine	on
	<Location	/>
		ProxyPass	http://127.0.0.1:3000/
		Order allow,deny
		Allow from all
		AuthName	"Your AD-credentials"
		AuthType	Basic
		AuthBasicProvider	ldap
		AuthLDAPInitialBindAsUser	on
		AuthLDAPInitialBindPattern	.+ $0@example.com
		AuthLDAPSearchAsUser	on
		AuthLDAPRemoteUserAttribute	sAMAccountName
		AuthLDAPURL	"ldaps://ad1.example.net ad2.example.net/OU=....,DC=example,DC=net?sAMAccountName?sub?(objectClass=*)"
		Require	valid-user
		RequestHeader	set Authorization "Token %{REMOTE_USER}e"
	</Location>
</VirtualHost>
```
The above snippet passes the authenticated user's `accessToken` to Uchiwa listening on 127.0.0.1. Some day, maybe, Uchiwa will even be able to do something useful with the username...

(With special thanks to @fessyfoo for figuring out the Token-authorization syntax in #540.)

**Comment by johntdyer** [comment]
I would love to see this in OSS version of Uchiwa...

**Comment by rankink** [comment]
@palourde - Regarding your comment on Apr 2, 2015, I have some questions that I would like to take you up on:

1. What would you prefer for the values of DriverFn and DriverName (in uchiwa/authentication/drivers.go) to be for LDAP authentication in order to prevent overlap with the Sensu Enterprise feature code?  Would ldap_community be best?
2. In my environment, I created a struct named Ldapconfig (in uchiwa/authentication/models.go) and populated that via passing the config data from config.Uchiwa.Ldap.* to the auth driver in uchiwa.go.  Where would you recommend that this occur?
3. I know that you are working on redoing logging.  How would you recommend that I align this with that effort in order to generate suitable logs?

**Comment by palourde** [comment]
Hi @rankink,

In order to ensure the maintainability of this project, I do not wish to maintain a codebase that duplicates an enterprise feature.

However, I've tried to make the authentication package as modular and flexible as possible in order to allow anyone to create their own authentication drivers. Therefore, you could create your own Uchiwa version with LDAP authentication, without having to duplicate the whole codebase, by simply copying the [uchiwa.go](https://github.com/sensu/uchiwa/blob/master/uchiwa.go) file and initializing the authentication driver just like this, for example:

```
package main

import "github.com/rankink/ldap"
[...]
func main() {
[...]
if config.Uchiwa.Auth.Driver == "ldap" {
  auth.Advanced(ldap.AuthorizationFunction, "ldap")
}	
[...]
}
```

The first parameter to pass to `auth.Advanced` is a function/method (here called _AuthorizationFunction_) with [this signature](https://github.com/sensu/uchiwa/blob/master/uchiwa/authentication/models.go#L11), where the first argument is the username, the second is the password and that returns whether a user or an error.

Let me know if you have any other question or you have any suggestion in order to improve the integration of authentication drivers in Uchiwa!

**Comment by johntdyer** [comment]
@palourde   -  Personally I would like it if the "username" field were just picked up via a header. I handle my auth in nginx and I can pass the username to Uchiwa as a header I just need it to honor it.

**Comment by jeffWelling** [comment]
Hey @rankink how goes with your Uchiwa LDAP auth adventure? I'm curious where you got to, I'd be happy to [try to] lend a hand, I'm eager to get LDAP auth working for my home network and have had problems with reverse proxies so far. Even if you didn't manage to get it all working, I'd be curious where you got to but I don't see an Uchiwa fork under your repo.

**Comment by joshbenner** [comment]
@palourde Would you accept contribution of a pipe-style auth provider? Or PAM?

**Comment by palourde** [comment]
@joshbenner External authentication is already offered in [Sensu Enterprise](https://sensuapp.org/docs/latest/enterprise/rbac/overview.html) so for this reason, we prefer to avoid duplication of features and the extra cost associated to the maintenance of additional code.

That being said, the good news is that RBAC will be added to the core of Sensu 2.0. However, until then, we are not planning to add anything in Uchiwa around external authentication since I will be mainly focussed on the next generation of Sensu.

Thanks!

**Comment by hanynowsky** [comment]
@UnitedMarsupials
I am able to use Apache ldap authentication but sounds like the ``` RequestHeader   set Authorization ``` instruction is doing nothing on the side of Uchiwa UI. (Same config as yours)
If I disable Uchiwa Users auth, it works fine and of course the logged-in user in Uchiwa is 'admin'.

Do you have any idea of what might be wrong?
I was expecting to see the name of the authenticated AD user on Uchiwa, instead of 'admin'.
