### ISSUE TITLE
Configure Uchiwa to use https authentication and add multiple users

### ISSUE THREAD

**Issue by hvyas** [sensu/uchiwa#341]
1) Configure Uchiwa to use https authentication (instead of plain http).
2) How to add multiple users?
3) How to integrate with Active Directory(AD) or LDAP.

**Comment by palourde** [comment]
Hi @hvyas 

1: I recommend you to perform SSL offloading with a reverse proxy such as nginx since there's no plan to add such feature within Uchiwa itself, due to complexity and security concerns.
2 & 3: These features are available in the [Sensu Enterprise Dashboard](https://sensuapp.org/enterprise)

Let me know if you have any other question.
