### ISSUE TITLE
Feature request: date picker for custom stash dates

### ISSUE THREAD

**Issue by eheydrick** [sensu/uchiwa#345]
It would be nice if there was a date picker on the custom stash creation screen. Sometimes you want to stash an alert until a particular day of the week. If the data picker was built-in you'd avoid having to look at a calendar outside the app.

**Comment by jbehrends** [comment]
+1

**Comment by ROunofF** [comment]
I'm not familiar with angular that much, which datepicker would you recommend?

I google this one: https://github.com/g00fy-/angular-datepicker ?

**Comment by eheydrick** [comment]
Not an angular person either, but found a few other options: 

http://angular-ui.github.io/bootstrap/
https://github.com/eternicode/bootstrap-datepicker/

**Comment by palourde** [comment]
https://github.com/g00fy-/angular-datepicker  - Date formatting doesn't seem possible
http://angular-ui.github.io/bootstrap/ - Only date, not datetime
https://github.com/eternicode/bootstrap-datepicker/ - Same, no datetime

**Comment by ROunofF** [comment]
We could combine the datepicker & timepicker from bootstrap? https://angular-ui.github.io/bootstrap/

As reference I found those 2 from JQuery : 
- http://xdsoft.net/jqplugins/datetimepicker 
- http://trentrichardson.com/examples/timepicker/

**Comment by jsoriano** [comment]
I have tried to implement this feature using the date and time pickers included in the angular directives for bootstrap (http://angular-ui.github.io/bootstrap/), as suggested by @ROunofF, because it seems that they are already included. But I'm not very into JS development and the result, although functional, is not very good :)
Any tip is welcome :)
The code is here https://github.com/jsoriano/uchiwa-web/tree/datetimepicker

**Comment by palourde** [comment]
This is now available in Uchiwa 0.23!
