### ISSUE TITLE
missing apt packages

### ISSUE THREAD

**Issue by heffergm** [sensu/uchiwa#396]
I haven't seen a new release in the apt repo since 0.10.3-1.

**Comment by palourde** [comment]
Hi @heffergm 

Unfortunately it seems that the build box used by the Sensu organization to push the packages to the repos crashed so a new one needs to be provisioned, which should be done within the next few days. Otherwise you can still download the packages from [Uchiwa website](https://uchiwa.io/#/download).

Thanks

**Comment by liamjbennett** [comment]
It appears that this is still an issue.

**Comment by palourde** [comment]
@liamjbennett the Sensu repository have been moved, please see https://sensuapp.org/docs/latest/install-repositories for the new address.
