### ISSUE TITLE
Convert event/client links to href

### ISSUE THREAD

**Issue by e1ven** [sensu/uchiwa#410]
I believe events are currently displayed as tr elements, with JS bound to them to respond to clicks.

``` <tr class="ng-scope" ng-repeat="event in filtered | buildEvents
| orderBy:predicate:reverse | limitTo:filters.limit track by event._id" ng-click="go('/client/'+event.dc+'/'+event.client.name+'?check='+event.check.name)">```

This prevents me from using a right-click to open the status on a new tab.

This [answer on Stack Overflow](https://stackoverflow.com/questions/23069481/how-to-allow-open-in-a-new-tab-when-using-ng-click) suggests changing the element to be a href, with a ng-click registered on it would might the current behavior, but also allow users to open a link in a new window/tab?

**Comment by palourde** [comment]
Hi @e1ven 

Unfortunately I can't simply replace/wrap a row (`<tr>`) with a link (`<a>`). I already tried few weeks ago to find a way around it but I was unsuccessful. If anyone has any idea, please let us know!

Meanwhile, I'll close this issue since we already have an [issue](https://github.com/sensu/uchiwa/issues/381) for this enhancement.

Thanks!
