### ISSUE TITLE
Silenced clients are not hidden, browser cache problem.

### ISSUE THREAD

**Issue by Gitnerd-1** [sensu/uchiwa#455]
Hi,

I have problems hiding silenced clients. They just don't hide. After upgrading to Uchiwa version 0.14.2, hiding silenced clients seemed to work just fine. The next day, I opened the Uchiwa events browser page, but the silenced clients were not hidden. Clicking the _"HIDE"_ drop down menu showed that the _"Silenced Clients"_ option was activated, but they were still being displayed. However, the _"Silenced Checks"_ option still worked.

After clearing the browser cache, hiding silenced clients started working again.
This is a bit annoying and happens every day or so. Is there a possibility to make the hiding user based and not "cookie/cache" based?

Example:
![image](https://cloud.githubusercontent.com/assets/17472134/13318025/b7ef3b74-dbb8-11e5-9fcd-13bcbfe8874e.png)

After refreshing my browser the "Silenced Clients" option is showing that it is deactivated. Activating the "Silenced Clients" option doesn't hide the clients, see picture above.

**Comment by HelioCampos** [comment]
OS: Ubuntu 14.04.3 LTS
sensu-[api|server|client]: 0.20.6
uchiwa: 0.14.2

I am having the same problem but regarding the action resolve. I solve the issues and ask uchiwa to solve it but they don't go away. I tried the following:
1) I really solved the issue in the machine that the alert sounded. No good;
2) I then tried to solve the problem using the action selecting the issues and selecting the action delete. It showed the green messages but didn't removed the alerts. No good;
3) I then tried to remove the server as sensu would include it again. It showed red messages. No good;
4) Stopped and started the sensu-client in the original machine the problem started. Also no good;
5) Stopped the sensu-client again, deleted the machine in uchiwa, started the service again. It showed red messages. No good;
6) Tried to find an answer on google and found this bug report;
7) Followed the comment to use another browser and the problem went away;
8) I tried again in the old browser and the problem was solved there without the need to clean the cache;

Now i have some doubts about this:
1) Was really a cache problem on my browser or in the integration with the sensu api?
2) Any action that i took could have solved the problem or i should just have waited something?

**Comment by palourde** [comment]
Hi @Gitnerd-1,

Could you let us know if you still face this issue with the latest release of Uchiwa? I'm currently unable to reproduce this issue, both clients and checks filters are now working properly.

Thanks!

**Comment by palourde** [comment]
Hi @HelioCampos,

Your issue looks related to https://github.com/sensu/uchiwa/issues/438. Could you try to upgrade to the latest Uchiwa release and let me know if you still face any issue?

Thanks
