### ISSUE TITLE
Uchiwa - Changing cookies of uchiwa_auth for Readonly = true/false gains full access for readonly user

### ISSUE THREAD

**Issue by sureshsubramaniam** [sensu/uchiwa#465]
When we change the cookie of the uchiwa_auth for a readonly user from true to false, the user can gain the readwrite access to the sensu data, is there a way we can stop these

Name%22%3A%22operator%22%2C%22Readonly%22%3Afalse%2C%22Subscriptions%22%3A%5B%5D%7D%2C%22

**Comment by palourde** [comment]
Hi @sureshsubramaniam,

If a user alter the uchiwa_auth cookie as you described, it only affects the content displayed; the user will still not be able to submit a stash or delete an event since the backend API uses the JWT (and not the cookie) to validate the access of any given user and would return a 403 response in this particular case.

Please let us know if you still have any question.
