### ISSUE TITLE
Uchiwa Client Status "API"

### ISSUE THREAD

**Issue by daytonturner** [sensu/uchiwa#501]
Hi there,

I was looking to extend what Uchiwa is able to show us about an overall client's health (a summary that represents the overall health, based on the cumulative results of all the checks)

I set out presuming that Sensu itself is tracking this information, whereby I could query the clients API for a particular client, and the status would be 0, 1, or 2 (OK, Warning, Critical) but after digging into the uchiwa code, it appears that uchiwa itself is handling this and concluding a "node health" status, independently of Sensu.

My question:  I would love to use this information in other tools (in my case, a Grafana Dashboard that shows a big green array of "UP" indicators, hopefully!), but I'm not sure if this is even really feasible, since uchiwa certainly wants an interactive browser talking to it (login, token, cookie, etc).

Can anyone think of a reasonably sane way to either script a query to uchiwa for this information for a given node, or retrieve it by some other means?

All input appreciated! :)

**Comment by palourde** [comment]
Hi,

Thanks for submitting this issue. I'm happy to announce that this is actually something we are actively working on so that Uchiwa can act as a "public" federated API for all Sensu APIs. The first step is to adjust all Uchiwa API routes so they match the Sensu API ones, which should be available within the 0.16.0 release. Then, we will tackle the authentication question in the 0.17.0 release since we currently use JSON Web Tokens (JWT) which make the use of third party clients difficult.

Meanwhile, you can still use the undocumented Uchiwa API if you disable the internal authentication (and possibly use a proxy for authentication instead). For example, you could access the clients list with this URL: `http://localhost:3000/clients` or a particular client with `http://localhost:3000/clients/$DATACENTER/$CLIENT_NAME`. Please note that some of these routes are expected to be modified in the next release but they will also be documented from that point.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa/pull/525
