### ISSUE TITLE
Feature Request: Stash until Keepalive/Check is OK

### ISSUE THREAD

**Issue by jasonpietrzak** [sensu/uchiwa#506]
Currently, when stashing a host or a check you can only have it automatically unstash after a period of time or by manually deleting the stash. I would like to see an option "until ok". Basically, upon success of a keepalive check or a check in general it would unstash the host and/or check.

Xymon is an example of a monitoring solution that does this perfectly. I would like to see this type of functionality built into Uchiwa.

**Comment by palourde** [comment]
This behavior would first need to be supported by the Sensu API. I believe it could be implemented through https://github.com/sensu/sensu/issues/1219.

**Comment by runningman84** [comment]
You could create a handler for keep alive events with resolve action and delete any corresponding stash.

**Comment by fessyfoo** [comment]
support for this is included in the proposal https://github.com/sensu/sensu/issues/1328 and pending implementation https://github.com/sensu/sensu/pull/1400 of built in silencing. 

uchiwa will need to support `expire_on_resolve` when being adapted to use the new built in silencing of sensu-server / api. 

this issue is duplicated by  similar proposal for sensu-plugin here https://github.com/sensu-plugins/sensu-plugin/pull/135

**Comment by josephholsten** [comment]
I thought `expire_on_resolve` was already here. Can we close this?

**Comment by fessyfoo** [comment]
yep latest versions of sensu-0.26 and [uchiwa-0.18](https://github.com/sensu/uchiwa/issues/539)  support `expire_in_resolve` via new built in silencing. 

recommend closing this.
