### ISSUE TITLE
Each client listed in all datacenters

### ISSUE THREAD

**Issue by yeeplusplus** [sensu/uchiwa#516]
I'm confused about which components need to be shared when creating separate sensu-server instances.  The goal is to be able to view two different groups of servers in the same uchiwa instance.

First, I tried creating on server A:
- sensu-server
- sensu-api
- redis
- rabbitmq
- uchiwa, with two datacenters (server A and server B)

server B:
- sensu-server
- sensu-api
- redis
- rabbitmq

client A1:
- sensu-client (pointing to server A's rabbitmq)

client B1:
- sensu-client (pointing to server B's rabbitmq)

This works, mostly, except that in the clients list in uchiwa I see each client listed twice (once for each datacenter).

I also tried pointing server B's redis.json to server A's redis port.  No change.

What do I need to do?

**Comment by palourde** [comment]
Hi @yeeplusplus 

Your setup seems to be good; make sure that the clients are pointing to the proper rabbitmq server and if possible, you could try to clear data on both redis servers (`redis-cli FLUSHALL`) just to make sure there's no irrelevant data left since you tried to use server A's redis with server B.

**Comment by yeeplusplus** [comment]
Thank you for the info on flushing redis.  I ran `redis-cli FLUSHALL` on both server A and server B, and reloaded the uchiwa page.  There was no change.

Then I restarted the redis process on each server, and it worked!  :smiley:
