### ISSUE TITLE
Uchiwa 0.16.0-1 fails to retrieve any client details

### ISSUE THREAD

**Issue by nhooey** [sensu/uchiwa#529]
With Uchiwa `0.16.0-1` and `0.17.0-1` from the Ubuntu Apt Repository, requesting this URL:
`https://<uchiwa_host>/#/client/Sensu/<client_name>`

Renders this:
`Could not retrieve the client <client_name> from the datacenter Sensu!`

This happens for _all_ Sensu clients we have.

This works without issue with Uchiwa `0.15.0-1` from the Ubuntu Apt repository. So the bug was introduced after Uchiwa `0.15.0-1`.

In all cases, Sensu Server and API are either all at version `0.25.3-1` or all at version `0.25.5-1` from the Ubuntu Apt Repository. (I tested all combinations of Uchiwa versions mentioned with the Sensu versions mentioned).

**Comment by palourde** [comment]
Hi,

Please make sure to follow these few steps when you upgrade: http://docs.uchiwa.io/en/latest/upgrading/ since some changes were introduced in the Uchiwa API starting from 0.16.0.

**Comment by fessyfoo** [comment]
Hi,  I want to add that we experienced the same issue.  (though we went from `0.14.0-1` to `0.17.0-1` ) 

Using Chrome's incognito mode the problem wasn't there.  clearing browser cache fixed the issue.  just reloading fixed the  issue for some users. 

since [cacheBreaker](https://github.com/sensu/uchiwa/blob/master/Gruntfile.js#L7) is done to all the assets in the [main page](https://github.com/sensu/uchiwa/blob/master/public/index.html)  I believe the issue is just the main page being in the browser cache. 

We had users report the issue at least 24hrs after the upgrade.

I further note that uchiwa's http response for the main page has no particular cache control settings:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2844
Content-Type: text/html; charset=utf-8
Last-Modified: Wed, 03 Aug 2016 17:17:04 GMT
Date: Fri, 05 Aug 2016 16:51:49 GMT
```

**Comment by fessyfoo** [comment]
it's unclear how long browsers ([such as chrome](http://stackoverflow.com/questions/9740822/how-long-does-google-chrome-cache-a-resource-if-expires-and-or-no-cache-headers) will cache that for. 

could just add some cache control headers to not cache that page, or setup an [HTML5 cache manifest](https://en.wikipedia.org/wiki/Cache_manifest_in_HTML5)

**Comment by palourde** [comment]
Thanks @fessyfoo for this insightful comment, I never realized the main page could provoke this issue by still being cached. I'll look into the possible fixes.

@nhooey By clearing all your cache browser for the time being, were you able to fix this issue?

**Comment by sbstnbr** [comment]
Hi @palourde  , I'm facing the same issue as @nhooey  - even after clearing my cache and going in Incognito mode.
