### ISSUE TITLE
Uchiwa 0.17.0: new clients not showing in dashboard, have to restart uchiwa daemon

### ISSUE THREAD

**Issue by marianogg9** [sensu/uchiwa#535]
Hi guys.
Still seeing this issue in this last version. Any ideas? Thanks!

Related to: https://github.com/sensu/uchiwa/issues/438 and all the others.

**Comment by palourde** [comment]
Hi @marianogg9,

Could you provide me more information about this specific issue since I'm currently unable to reproduce it? Do you have anything relevant in the Uchiwa logs or the browser console? If you access the Uchiwa backend API (e.g. http://localhost:3000/clients, you might have to disable authentication or use an [access token](http://docs.uchiwa.io/en/latest/features/federated-api/#authentication)), do you see the new clients?

Thanks

**Comment by marianogg9** [comment]
Hi @palourde 
Sorry, got it now. I've decreased the refresh time and it's working just fine now.

Thanks!
