### ISSUE TITLE
uchiwa not showing checks

### ISSUE THREAD

**Issue by SiKing** [sensu/uchiwa#553]
I have a Sensu server, monitoring only one client, for now. I have several checks defined. The .json for each check is in /etc/sensu/conf.d on **both** the server and the client. The checks are working correctly, and I can see expected failures under both the client and event tabs in uchiwa. However, the checks tab is completely empty.
How do I get the checks defined on the server to show up in the uchiwa dashboard?

**Comment by palourde** [comment]
Hello @SiKing,

In order to determine whether it's an issue with Uchiwa or possibly your configuration, could you try to reach the Sensu API on the following endpoint (make sure to adjust the host to your Sensu API) and provide us the result? `http://sensu-api:4567/checks`.

If the list is empty, then you Sensu server is simply unaware of these checks and you should try to investigate your configuration. Please note that standalone checks will not appear there so it might explain the behaviour you are facing.

However, if you do have some content but it does not show up in Uchiwa, please respond to this issue with some traces of your investigation since it would be a bug.

**Comment by SiKing** [comment]
The checks API comes back empty, so this appears to be a problem with my configuration.
I am still new to Sensu, and not sure what "standalone checks" are and what option is there.

**Comment by sufiyanghori** [comment]
This issue is similar to, https://github.com/sensu/sensu/issues/1775
Standalone checks are not visible in checks list and this is expected behavior.
