### ISSUE TITLE
Silencing does not actually work

### ISSUE THREAD

**Issue by Gillingham** [sensu/uchiwa#560]
Uchiwa 0.18.0
Sensu 0.26.1

### Steps to reproduce

1. Confirm there are no silenced entries prior:

    ```
curl -s http://localhost:4567/silenced | jq
[]
    ```
2. Visit the events page, silence a source on it, set No expiration and Expire on Resolve then click Submit.
3. Confirm uchiwa shows the green success box.
4. Confirm the request got to the API

    ```json
{"timestamp":"2016-09-09T00:09:24.856053+0000","level":"info","message":"api response","request":{"remote_address":"172.17.0.5","user_agent":"Go-http-client/1.1","method":"POST","uri":"/silenced","query_string":null,"body":"{\"id\":\"\",\"dc\":\"MSP\",\"subscription\":\"client:ctt\",\"expire\":-1,\"expire_on_resolve\":true}\n\n"},"status":201,"content_length":0}
    ```
5. Check the silenced API to see that no silence actually got created:

    ```
curl -s http://localhost:4567/silenced | jq
[]
    ```

#### The API directly still functions, the breakage is in uchiwa
```
$ curl -s http://localhost:4567/silenced | jq
[]
$ curl -s -i -X POST -H 'Content-Type: application/json' -d '{"subscription": "client:ctt", "expire_on_resolve": true }' http://localhost:4567/silenced
HTTP/1.1 201 Created
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-length: 0

$ curl -s http://localhost:4567/silenced | jq
[
  {
    "id": "client:ctt:*",
    "subscription": "client:ctt",
    "check": null,
    "reason": null,
    "creator": null,
    "expire_on_resolve": true,
    "expire": -1
  }
]
```
The API log from that request is
```json
{"timestamp":"2016-09-09T00:11:27.422279+0000","level":"info","message":"api response","request":{"remote_address":"127.0.0.1","user_agent":"curl/7.29.0","method":"POST","uri":"/silenced","query_string":null,"body":"{\"subscription\": \"client:ctt\", \"expire_on_resolve\": true }"},"status":201,"content_length":0}
```

**Comment by josephholsten** [comment]
I can confirm.

**Comment by johntdyer** [comment]
The logs on the request from uchiwa seems to have an extra quote around the Boolean value for expire_on_resolve.

**Comment by GuitarrasDeAmor** [comment]
I was going to create another issue but will just post here as I feel it may be related. If not I can create a separate issue if anybody wants to chime in as to whether or not it is.

Last night puppet upgraded Uchiwa to 0.18.0, and this morning I am noticed that I did not see any hosts on the event page, even though I saw there were 7 in critical/warning state. Curious, I clicked the "Hide" dropdown and "Silenced Checks" and "Silenced Clients" buttons, and sure enough all the checks that were alerting showed back up. So instead of just hiding stashed clients/checks, both of those options hide all hosts on the Events page.

**Comment by amdprophet** [comment]
We've confirmed that there is a bug with silencing clients/checks with Uchiwa and are working on a fix.

**Comment by stevenviola** [comment]
@GuitarrasDeAmor I think your issue is separate. I'm seeing the same thing on the Events page with 0.18.0 where hiding silenced checks silenced clients hides all events on the page, regardless if they're silenced or not. Additionally, if a client of check is silenced, it is no longer indicated on the events page.

**Comment by amdprophet** [comment]
Uchiwa 0.18.1 is now live with a fix for the creation of stashes with no expiry. There is a separate issue around JIT/proxy clients in Sensu Core being tracked in https://github.com/sensu/sensu/issues/1439.
