### ISSUE TITLE
silenced checks not highlighted in events view

### ISSUE THREAD

**Issue by lobeck** [sensu/uchiwa#566]
Uchiwa 0.18.1
Sensu 0.26.1

Silenced checks no longer have the red icon as in previous versions. This still works for hosts (silenced hosts have the red icon) however this does not apply for checks.

Maybe this is related to #565

**Comment by stevenviola** [comment]
When hitting the Sensu events api endpoints (using Sensu 0.26.1), there are fields for silenced and silenced by, which for me always returns false. I think Uchiwa is looking at these fields when displaying the icon, and since silenced is always false, it doesn't show the icon.

This can be checked by silencing alerts, and then checking the output from the Sensu API:

`curl -s http://127.0.0.1:4567/events | jq .[].silenced`

It's possible that this is something that needs to be fixed in Sensu Core.

**Comment by bootswithdefer** [comment]
Silenced checks seem to show up correctly for me for the first Sensu API endpoint I have defined in uchiwa.json, but additional ones are hit and miss.  Some of the show up with the icon, others don't.

**Comment by bootswithdefer** [comment]
I just noticed my working clients are on 0.26.1 but my non-working clients are 0.25.x.  When I updated the old one suddenly the check started showing up with the red icon.

**Comment by lobeck** [comment]
You're right, just noticed that the affected clients didn't get the update. As they've got it now, the icons changed.

**Comment by josephholsten** [comment]
so I'm not sure this should qualify as closed. When I go to the individual event page, the event shows the correct "silenced" status, but on the event index the status is incorrect.

I'm concerned that they're using different code paths to determine if a client or event is silenced.

**Comment by stevenviola** [comment]
@bootswithdefer is correct, when I updated the clients to 0.26.1, the events endpoint does return the expected response and correctly identifies the checks as silenced, even if the host is not silenced. In the events page in Uchiwa, this is correctly identified with the red silenced icon.

**Comment by josephholsten** [comment]
when I look at an event page, the checks returned from uchiwa in a `/clients/{client-name}/history` response have the correct value for `silenced`, but the checks returned from an `/events` seem to reflect this bug.

Honestly, I don't care if we say that this is sensu's problem, but it worries me that these don't match.

**Comment by stevenviola** [comment]
@josephholsten What version of sensu client is running for the checks you're silencing? On the client page, does it say you're running that version (on the left where the client defination is displayed). For me, I didn't restart sensu-client after upgrading. After restarting the sensu-client, I was seeing expected behavior in Uchiwa and from the Sensu API

**Comment by bootswithdefer** [comment]
@josephholsten When I query /clients/{client}/history I don't even see a silenced key.  Is yours under the top level of history or under last_result?  If the latter, do you have a silenced key silenced defined in your checks?

**Comment by josephholsten** [comment]
@stevenviola: the silenced key is missing from uchiwa `/events` for nodes that have sensu-client version: 0.20.3. it's present for nodes with version: 0.26.1.

I was just looking at the sensu-api output for `/clients/{client}/history`, and I don't see a `silenced` key, I only see it from the uchiwa response. 

it's item level, looks like it's being added by https://github.com/sensu/uchiwa/blob/master/uchiwa/client.go#L27

**Comment by josephholsten** [comment]
@palourde could you take a look at this, looks like you're the last person to touch this stuff
