### ISSUE TITLE
Question - How to assemble checks as groups so that it is possible to show green, yellow or red blocks

### ISSUE THREAD

**Issue by 030** [sensu/uchiwa#575]
For example in opsview this is possible: https://knowledge.opsview.com/storage/attachments/209-int2.png

It this also possible in uchiwa?

**Comment by palourde** [comment]
Thank you for opening this issue.

Unfortunately, there's currently no overview dashboard available in Uchiwa. There's an [issue](https://github.com/sensu/uchiwa/issues/75) to track any progress made about it.

Otherwise, [Sensu Enterprise Console](https://sensuapp.org/enterprise) offers a Heads Up Display (HUD) that could interest you.

Thanks
