### ISSUE TITLE
Feature request: Add stash until value changes and until status changes

### ISSUE THREAD

**Issue by andrewinHK** [sensu/uchiwa#578]
These two options would be very handy to ensure alerts are not stashed longer than necessary.  Adding it to the API would be a bonus!

**Comment by palourde** [comment]
For reference, the new silences entries in Sensu 0.26+ support the `expire_on_resolve` attribute, which will automatically remove an entry if an event is resolved.

If it doesn't correspond to your needs, feel free to open an issue on the [Sensu](https://github.com/sensu/sensu) repository since it would first need to be supported by the Sensu API before being implemented in Uchiwa.

Thanks
