### ISSUE TITLE
Uchiwa always shows error

### ISSUE THREAD

**Issue by maestrofx** [sensu/uchiwa#590]
Hi there,

I always get error like this:

> Oops! Something went wrong.
Uchiwa is having trouble updating its data. Try to refresh the page if this issue persists.

version: 0.19.0
no error in 
```
# tail -f /var/log/uchiwa.err  
# tail -f /var/log/uchiwa.log 
```

any advice?

Thank you

**Comment by tibra** [comment]
I'm having the same error. Uchiwa log indicates that it can't connect to the sensu-api
`"timestamp":"2016-11-03T07:31:22.55451375+01:00","level":"info","message":"Updating the datacenter Sensu"}
{"timestamp":"2016-11-03T07:31:22.557164486+01:00","level":"warn","message":"GET http://127.0.0.1:4567/silenced returned: 404 Not Found"}
{"timestamp":"2016-11-03T07:31:22.557186353+01:00","level":"warn","message":"Connection failed to the datacenter Sensu."}` 

On this standalone installation, I can request a `curl -vv http://127.0.0.1:4567/silenced` and I'm getting a 404 indeed, but `curl -vv http://127.0.0.1:4567/**checks**` works just fine. The sensu-api seems to respond to the Uchiwa requests, but since the request_body ist empty, there is nothing to report back I guess:
`{"timestamp":"2016-11-03T07:36:32.556414+0100","level":"info","message":"GET /silenced","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"GET","request_uri":"/silenced","request_body":""} `

I'm wondering wether I'm misinterpreting the logs or if I've just missed an important part.

**Comment by palourde** [comment]
As stated in the [Uchiwa changelog](https://github.com/sensu/uchiwa/blob/master/CHANGELOG.md#0180-2016-09-07), Sensu 0.26 is required since the 0.18 release of Uchiwa. Stashes are now indeed deprecated in favour of silenced items.

I'll make some changes to make it obvious in the log files that a Sensu version is no longer supported.

Thanks

**Comment by dwagon** [comment]
I'm still getting the "Oops"

Latest versions of everything:
- sensu-0.26.3-1.x86_64
- uchiwa-0.20.0-1.x86_64

Nothing in uchiwa.err
This in uchiwa.log on startup, no failures indicated:
```
{"timestamp":"2016-11-16T17:04:47.381208305+09:30","level":"warn","message":"Loading the configuration file /etc/sensu/uchiwa.json"}
{"timestamp":"2016-11-16T17:04:47.386170795+09:30","level":"warn","message":"Uchiwa is now listening on 0.0.0.0:3000"}
```

Uchiwa itself is working and connecting to the sensu and displaying hosts etc.
If I break the uchiwa.json file it doesn't start - so it is definitely reading it.
The config displayed on the info page is the internal config and not from the config files.

**Comment by shankerbalan** [comment]
Same here, it is working fine in one of my deployments but on the other one, even after upgrading all clients to sensu 0.26.5 (CentOS), the problem persists.

**Comment by palourde** [comment]
@dwagon @shankerbalan The `Oops! Something went wrong.` error message have been modified in 0.20 so if you still receive this message, it leads me to believe that the JS stuff is still cached in your browser and causing this issue. Please make sure to clear your cache or try with some other browser and let us know!

Meanwhile, we'll investigate the caching issues in order to avoid these type of issues after an upgrade.

**Comment by dwagon** [comment]
Clearing the cache fixed the problem :)

Thanks

**Comment by palourde** [comment]
Awesome! I just pushed a patch that will automatically prevent the browser from caching the index.html file, which is causing all this trouble.
