### ISSUE TITLE
Feature Request: Silencing keepalive "check" for entire datacenter

### ISSUE THREAD

**Issue by jaykumar-jnpr** [sensu/uchiwa#611]
Currently Uchiwa provides functionality to create Silence based on Subscription and Checks for a datacenter, but there is no way to Silence keepalive "check" for entire datacenter.

* Uchiwa version used: 0.20.2
* Sensu version used: 0.26.3
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7

**Comment by kronkite115** [comment]
My current understanding is that if you have a subscription that is shared for every client in a DC then you can silence the DC by using that subscription.  The shortcoming I see is JIT clients that don't have subscriptions.  At the very least those don't make too much noise by default.

Currently I'm experimenting with a registration handler that adds a subscription for JIT clients so I can silence them with the rest of the DC.

What I would like to see instead is the ability to filter a DC in Uchiwa.

**Comment by palourde** [comment]
@jaykumar-jnpr I think @kronkite115 suggestion is the most appropriate one. Uchiwa itself has no way to achieve that otherwise.

@jaykumar-jnpr If you wish to exclude a single datacenter in a view, you could use a [negative lookahead](https://docs.uchiwa.io/guides/search-queries/#negative-lookahead), such as `dc:^((?!us-east-1).)*$`.
