### ISSUE TITLE
Output column is blank on client view since 0.20.0

### ISSUE THREAD

**Issue by br0ch0n** [sensu/uchiwa#612]
## Expected Behavior
Column shows the output of each check on 

## Current Behavior
Column shows no output on any of the checks

## Possible Solution
I suspect this happened in the refactor in https://github.com/sensu/uchiwa-web/commit/c42793931bf6d64a5ed5fec396576d208fe3fd6d#diff-c050398d39586221bc1d98b55bd0a7a9 but haven't dug in enough to confirm.  Would make sense since this is broken in 0.20.0

## Steps to Reproduce (for bugs)
Run uchiwa 0.20.2 and look at an individual client's view (i.e. /client/(datacenter)/(clientname), not /clients which BTW works fine).  If you then click on a check, the output does show up in the check view just fine.  
Tested using the 0.19.0, 0.20.0 and 0.20.2 docker images.  

## Context
Looks fine when downgrading to 0.19.0

## Your Environment

* Uchiwa version used: 0.20.2
* Sensu version used: 0.26.3
* Operating System and version (e.g. Ubuntu 14.04): Ubuntu 16.04

**Comment by br0ch0n** [comment]
Thanks!

**Comment by xyntrix** [comment]
Update from 0.20.2 -> 0.23.0 fixed this for us, however it wasn't working until I let the browser cache expire (took a few minutes). A simple shift-refresh didn't help and if I went into incognito mode, I could see the fix was applied.   Is there a reference somewhere for what does/does not get cached by a browser?  It'd be great if there was maybe a UI button to force clearing of the local browser's cache for Uchiwa, without having to go into developer tools or other hurdles.     Thanks!

**Comment by palourde** [comment]
@xyntrix We just released [0.23.1](https://github.com/sensu/uchiwa/blob/master/CHANGELOG.md#0231-2017-03-29) which we hope will definitively solve any caching issues after an upgrade. Please let us know how it goes and if you still face any issue!

Thanks
