### ISSUE TITLE
Uchiwa 0.23.0-1 not found, tried to install yum_repo

### ISSUE THREAD

**Issue by Ksreenivas** [sensu/uchiwa#671]
Hi @palourde 

I am pretty excited to install the Uchiwa newer version but not able to do so.
Can someone please have a look at my issue.

FYI
I even tried to install with uchiwa version 0.23.0-1.el7 with release still the same.
Right now i am using uchiwa cookbook version 1.0.0 
Below is the error log generated
#######
Error executing action `install` on resource 'yum_package[uchiwa]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    Version 0.23.0-1 of uchiwa not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/uchiwa/recipes/repo.rb
    
     56: package 'uchiwa' do
     57:   options package_options
     58:   version node['uchiwa']['version']
     59: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/uchiwa/recipes/repo.rb:56:in `from_file'
    
    yum_package("uchiwa") do
      package_name "uchiwa"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "uchiwa"
      recipe_name "repo"
      flush_cache {:before=>false, :after=>false}
      version "0.23.0-1"
      options "--nogpgcheck"
    end
    
    Platform:
    ---------
    x86_64-linux
    

Running handlers:
  - Chef::Handler::SlackReporting
Running handlers complete
Chef Client failed. 9 resources updated in 34 seconds
#######

**Comment by Evesy** [comment]
This is due to the fact that the latest cookbook release (1.2.0) does not include the updated repository URL's, and as such the package is not found.

The relevant changes have been committed (See https://github.com/sensu/uchiwa-chef/pull/53) however a new version is yet to be released (See https://github.com/sensu/uchiwa-chef/issues/54)

I'm not sure if it's possible to override the repo URL as it's not entirely attribute driven, however you could switch to the http install method in the meantime. Simply include the default uchiwa recipe in your run list and set the following attributes:

```
default['uchiwa']['install_method'] = 'http'
default['uchiwa']['http_url'] = 'http://dl.bintray.com/palourde/uchiwa'
default['uchiwa']['version'] = '0.23.0-1'
```
