### ISSUE TITLE
Add feature to hide metrics from clients/events view

### ISSUE THREAD

**Issue by meloos** [sensu/uchiwa#707]
I would like to see a feature in uchiwa to hide metrics from views

## Expected Behavior
Cleaner view in clients/events dashboard, without metrics checks

## Current Behavior
Overload of information, too many checks, because of not so useful in many cases info from metric checks

## Possible Solution
- on/off filter for metrics check
- on/off filter based on some check definition variables, ex. : 
"linux_load_avarage_metrics": {
      "command": "metrics-load.rb",
      "subscribers": [
        "linux"
      ],
      "output_type": "graphite",
      "auto_tag_host": "yes",
      "type": "metric",
      **"hide": "true",**
      "handlers": [ "relay" ],
      "interval": 60
    },

**Comment by palourde** [comment]
Hi @meloos, sorry for the delayed response, I was in vacation for the past few weeks!

It seems we already have an issue for this feature (https://github.com/sensu/uchiwa/issues/310) so I'll go ahead and close this one to prevent duplication.

For reference, I'll add this feature into the Uchiwa 0.26 milestone since it should now be relatively easy to implement.

Thanks
