### ISSUE TITLE
Is it possible to add a custom theme?

### ISSUE THREAD

**Issue by pietervogelaar** [sensu/uchiwa#727]
In the Uchiwa dashboard I can select the theme "uchiwa-default" or "uchiwa-dark". Is it possible to add a custom theme there? 

What would be the required steps?

**Comment by palourde** [comment]
Hi,

Uchiwa uses [Sass](http://sass-lang.com/) to generate the CSS, which allows multiple themes without much effort. As you can see [here](https://github.com/sensu/uchiwa-web/tree/master/css/uchiwa-dark), the _uchiwa-dark_ theme is based on _uchiwa-default_ and only specify the differences between these two themes.

In order to create your own theme, you would need to fork and clone this project, create a new directory similar to _uchiwa-dark_ and finally, build the stylesheets using the command `grunt sass`. To do so, you will need to make sure to follow these [instructions](https://docs.uchiwa.io/getting-started/installation/#from-source) so you have all the required tooling. From this point, the harder part would be to add your theme to the available options, which would require you to modify the siteTheme directive: https://github.com/sensu/uchiwa-web/blob/cd38721aff5b5546191efc888255766e68b3cba5/js/directives.js#L224.

Some heavy lifting would probably required to support external themes unfortunately.

Let me know if you have any questions.

Thanks
