### ISSUE TITLE
persistent datacenter parameter

### ISSUE THREAD

**Issue by exeral** [sensu/uchiwa#766]
Keep the datacenter filtering across navigation between pages
This is an improvement/suggestion.

## Expected Behavior
the datacenter value from the datacenter dropdown filter should be kept across navigation between different pages

## Current Behavior
If you click on a detailed view and go back to event view. the datacenter filter has been reset to default (all)
same if you switch between view in the left pane

## Possible Solution
pass the GET parameter "?dc=" in each url ..?

## Steps to Reproduce (for bugs)
1. Go to events view
2. choose a datacenter in dropdown list
3. click on left pane on clients view

## Context
We have a unique Uchiwa for different teams.
each team has its own sensu infrastructure. all these sensu infra are gathered in Uchiwa.
but they should be able to browse uchiwa while keeping their scope of work.

This idea could be applied to the other filters maybe ?

## Your Environment
Linux Fedora 27
Google Chrome Version 64.0.3282.167 (Build officiel) (64 bits)
Sensu 1.1.2
Uchiwa 0.26.3

**Comment by palourde** [comment]
Hi @exeral,

We already have an issue open for that feature request: https://github.com/sensu/uchiwa/issues/156, so I'll close this one in order to avoid duplication.

As you might be aware, with the development of Sensu 2.0 in full swing, Uchiwa 1.x development efforts are now focused on minor features, bug fixes, and security patches. Therefore, this is not something I will personally work on but if anyone is interested in implementing that functionality, I'll gladly provide some assistance.

Thanks
